# Architecture identifier.
arch = "riscv64"
# Platform identifier.
platform = "fpga-cyysoc"

# Base address of the whole physical memory.
phys-memory-base = "0x8000_0000"
# Size of the whole physical memory.
phys-memory-size = "0x8000_0000" # 2 GiB
# Base physical address of the kernel image.
kernel-base-paddr = "0x8020_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_ffc0_8020_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_ffc0_0000_0000"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    ["0x6010_0000", "0x1000"], # UART
    ["0x6020_0000", "0x10_0000"], # ETH0
    ["0x6030_0000", "0x10_0000"], # AXI_ETH_DMA
    ["0x0200_0000", "0x1_0000"], # CLINT
    ["0x0c00_0000", "0x400_0000"], # PLIC
    ["0x6000_0000", "0x2000_0000"] # AXI4
]
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = []
# Base physical address of the PCIe ECAM space.
pci-ecam-base = "0"
# End PCI bus number.
pci-bus-end = "0"
# PCI device memory ranges.
pci-ranges = []

# Timer interrupt frequency in Hz.
timer-frequency = "100_000_000" # 100 MHz
